version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: nexus_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=nexus
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-nexus123}
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_MANAGEMENT_DISABLED=false
      - N8N_WEBHOOK_URL=http://localhost:5678/
      - WEBHOOK_TUNNEL_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows
    networks:
      - nexus_network

volumes:
  n8n_data:

networks:
  nexus_network:
    driver: bridge
