# Dual Display Layout Configuration
display_count: 2
layout_strategy: "dual_focus"

displays:
  left:
    id: 1
    name: "Secondary Display"
    purpose: "Reference & Communication"
    layout: "bsp"
    apps: ["Safari", "Chrome", "WhatsApp", "Slack", "Obsidian"]
    
  right:
    id: 2
    name: "Primary Display"
    purpose: "Main Work & AI Tools"
    layout: "bsp"
    apps: ["Visual Studio Code", "Terminal", "ChatGPT", "Grok", "LM Studio"]

workspace_profiles:
  work:
    left_apps: ["Safari", "Slack", "Teams"]
    right_apps: ["Visual Studio Code", "Terminal", "ChatGPT"]
    
  personal:
    left_apps: ["WhatsApp", "Spotify", "YouTube"]
    right_apps: ["Obsidian", "Safari", "Calendar"]
    
  ai_research:
    left_apps: ["Documentation", "Research Papers"]
    right_apps: ["Jupyter Notebook", "LM Studio", "Terminal"]

# YABAI Rules for Dual Display
yabai_rules:
  - "yabai -m rule --add app=\"Safari\" display=1"
  - "yabai -m rule --add app=\"WhatsApp\" display=1"
  - "yabai -m rule --add app=\"Slack\" display=1"
  - "yabai -m rule --add app=\"Visual Studio Code\" display=2"
  - "yabai -m rule --add app=\"Terminal\" display=2"
  - "yabai -m rule --add app=\"ChatGPT\" display=2"
